### ISSUE TITLE
.useAngularHttp() with request options

### ISSUE THREAD

**Issue by igler** [traverson/traverson-angular#18]
The following statement does not work, as there are no headers send with the request:

<pre><codoe>traverson
    .from(location._links.self.href)
    .useAngularHttp()
    .withRequestOptions({
        headers: {
            'Content-Type': 'application/hal+json',
            'If-Match': location.version
        }
    })
    .put(location)
    ....
</code></pre>

Does <code>withRequestOptions</code> work with Angular's <code>$http</code>?

**Comment by igler** [comment]
Well, as I know the link I could also do it directly with $http:
<pre><code>$http
    .put(location._links.self.href, location, {
        headers: {
            'Content-Type': 'application/hal+json',
            'If-Match': location.version
        }
    })
    .then(function (document) {
    ...
</code></pre>

**Comment by basti1302** [comment]
This fell a bit through the cracks :D (lol close to three years). While I can not rule out that there was an issue with that in 2015, it certainly works like a charm in the current version: https://github.com/traverson/traverson-angular/commit/84989f414cd31d9bc6404dcfa0e1b58679a0520a#diff-068b98f1dc7cd889fe62c335160e071dR661
