### ISSUE TITLE
Angular 2 support?

### ISSUE THREAD

**Issue by sumitzamadar** [traverson/traverson-angular#35]
Does this support angular 2/4?

**Comment by basti1302** [comment]
No, this is Angular 1.x. As far as I know, no one has implemented an Angular >= 2 integration. I won't do that either but would be willing to help if someone wants to work on that.

**Comment by sumitzamadar** [comment]
I'm using Traverson in Angular 4 project.
I'm stuck in writing the unit test for the service where Traverson is being used. 
I didn't find any solution how to mock the http call.

Any help...?

**Comment by sumitzamadar** [comment]
Also I would like to intercept before Traverson actually calls the API, so that I can do some stuff like to check the session etc.

**Comment by basti1302** [comment]
Unfortunately I don't have any Angular2 expertise, so I can't really help here. I'll leave the ticket open for a while in case someone with more knowledge can help.
